import os
import re
import shutil
import urllib.request
import zipfile

# ==============================================================================
# CONFIGURATION
# ==============================================================================
REPO_OWNER = "TaurusTLS-Developers"
REPO_NAME = "OpenSSL-Distribution"
# Where to extract files relative to Repo Root
TARGET_DIR = os.path.join("lib", "openssl")

# Versions to install
TARGET_VERSIONS =["3.0.19", "3.3.6", "3.4.4", "3.5.5", "3.6.1"]

# Platforms to install mapped to exact OpenSSL-Distribution artifact suffixes
TARGET_PLATFORMS = {
    "Windows-x64.zip":     "Win64",
    "Windows-x86.zip":     "Win32",
    "Windows-arm64ec.zip": "Win64ARM",
    "Linux-x64.zip":       "Linux64",
    "Linux-arm64.zip":     "LinuxARM64",
    "macOS-universal.zip": "OSX",          # Extracts unified zip to single OSX folder
    "Android-arm64.zip":   "Android64",
    "Android-arm.zip":     "Android",      # 32-bit Android
    "iOS-arm64.zip":       "iOSDevice64",
    "iOS-sim-arm64.zip":   "iOSSimARM64"
}

# ==============================================================================
# LOGIC
# ==============================================================================
def log(msg):
    print(f"[SETUP] {msg}")

def download_file(url, dest_path):
    log(f"Downloading {url}...")
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response, open(dest_path, 'wb') as out_file:
            shutil.copyfileobj(response, out_file)
        return True
    except Exception as e:
        log(f"Download failed: {e}")
        return False

def extract_archive(archive_path, extract_to):
    log(f"Extracting to {extract_to}...")
    os.makedirs(extract_to, exist_ok=True)
    
    with zipfile.ZipFile(archive_path, 'r') as z:
        z.extractall(extract_to)

def generate_version_inc(actual_version, target_dir):
    """
    Generates 'ossl_version_scope.inc' inside the lib/static directory.
    Example Content: 
    {$DEFINE OSSL_3_6}
    {$DEFINE OSSL_STRICT_3_6}
    """
    # Parse Major.Minor (e.g. 3.6.1 -> 3.6)
    match = re.match(r'^(\d+)\.(\d+)', actual_version)
    if not match:
        log(f"WARNING: Could not parse version '{actual_version}' for define generation.")
        return

    major, minor = match.groups()
    define_str = f"{major}_{minor}"
    
    # Target directory for the include file: <platform_dir>/lib/static/
    inc_dir = os.path.join(target_dir, "lib", "static")
    os.makedirs(inc_dir, exist_ok=True)
    inc_path = os.path.join(inc_dir, "ossl_version_scope.inc")

    with open(inc_path, "w") as f:
        f.write(f"// Auto-generated by setup_libs.py for OpenSSL {actual_version}\n")
        f.write(f"{{$DEFINE OSSL_{define_str}}}\n{{$DEFINE OSSL_STRICT_{define_str}}}\n")
    
    log(f"Generated version include: OSSL_{define_str} and OSSL_STRICT_{define_str}")

def main():
    # 1. Resolve Paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    base_lib_dir = os.path.join(repo_root, TARGET_DIR)
    temp_dir = os.path.join(repo_root, "_temp_deps")

    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)

    # 2. Iterate Versions
    for expected_version in TARGET_VERSIONS:
        # Construct Tag Name
        tag = f"v{expected_version}"
        
        for suffix, local_plat in TARGET_PLATFORMS.items():
            # Construct Asset Name
            asset_name = f"openssl-{expected_version}-{suffix}"
            download_url = f"https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/download/{tag}/{asset_name}"
            
            local_archive = os.path.join(temp_dir, asset_name)
            
            # Download
            if download_file(download_url, local_archive):
                # Target: <repo_root>/lib/openssl/<version>/<platform>/
                final_dest = os.path.join(base_lib_dir, expected_version, local_plat)
                
                # Clean up existing directory if present before fresh extraction
                if os.path.exists(final_dest):
                    shutil.rmtree(final_dest)
                    
                # Extract "as is" directly to destination
                extract_archive(local_archive, final_dest)
                
                # Check for version.txt
                version_txt_path = os.path.join(final_dest, "version.txt")
                if not os.path.exists(version_txt_path):
                    log(f"WARNING: version.txt not found in {asset_name}. Skipping include file generation.")
                else:
                    with open(version_txt_path, "r") as vf:
                        actual_version = vf.read().strip()
                        
                    # Compare extracted version against expected version
                    if actual_version != expected_version:
                        log(f"WARNING: Version mismatch! Expected '{expected_version}' but found '{actual_version}' in version.txt.")
                        
                    # Generate Version Include File using the version found in version.txt
                    generate_version_inc(actual_version, final_dest)
                
                log(f"Installed {expected_version} for {local_plat}")
            else:
                log(f"Skipping {expected_version} {local_plat} (Not found or error)")

    # Cleanup
    shutil.rmtree(temp_dir)
    log("Dependency setup complete.")

if __name__ == "__main__":
    main()