import os
import re
import shutil
import urllib.request
import zipfile

# ==============================================================================
# CONFIGURATION
# ==============================================================================
REPO_OWNER = "TaurusTLS-Developers"
REPO_NAME = "OpenSSL-Distribution"
# Where to extract files relative to Repo Root
TARGET_DIR = os.path.join("lib", "openssl")

# Versions to install (Fixed the trailing dot on 3.4.4)
TARGET_VERSIONS =["3.0.19", "3.3.6", "3.4.4", "3.5.5", "3.6.1"]

# Platforms to install mapped to new OpenSSL-Distribution .zip naming
TARGET_PLATFORMS = {
    "windows-x64.zip":   "Win64",
    "windows-x86.zip":   "Win32",
    "linux-x64.zip":     "Linux64",
    "macos-x64.zip":     "OSX64",
    "macos-arm64.zip":   "OSXARM64",
    "android-arm64.zip": "Android64",
    "ios-arm64.zip":     "iOSDevice64"
}

# ==============================================================================
# LOGIC
# ==============================================================================
def log(msg):
    print(f"[SETUP] {msg}")

def download_file(url, dest_path):
    log(f"Downloading {url}...")
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response, open(dest_path, 'wb') as out_file:
            shutil.copyfileobj(response, out_file)
        return True
    except Exception as e:
        log(f"Download failed: {e}")
        return False

def extract_archive(archive_path, extract_to):
    log(f"Extracting to {extract_to}...")
    os.makedirs(extract_to, exist_ok=True)
    
    with zipfile.ZipFile(archive_path, 'r') as z:
        z.extractall(extract_to)

def generate_version_inc(version, target_dir):
    """
    Generates 'ossl_version_scope.inc' inside the lib/static directory.
    Example Content: {$DEFINE OSSL_3_3}
    """
    # Parse Major.Minor (e.g. 3.3.6 -> 3.3)
    match = re.match(r'^(\d+)\.(\d+)', version)
    if not match:
        log(f"Could not parse version '{version}' for define generation.")
        return

    major, minor = match.groups()
    define_str = f"{major}_{minor}" # e.g. 3_3
    
    # Target directory for the include file: <platform_dir>/lib/static/
    inc_dir = os.path.join(target_dir, "lib", "static")
    os.makedirs(inc_dir, exist_ok=True)
    inc_path = os.path.join(inc_dir, "ossl_version_scope.inc")

    with open(inc_path, "w") as f:
        f.write(f"// Auto-generated by setup_libs.py for OpenSSL {version}\n")
        f.write(f"{{$DEFINE OSSL_{define_str}}}\n{{$DEFINE OSSL_STRICT_{define_str}}}\n")
    
    log(f"Generated version include: OSSL_{define_str}")

def main():
    # 1. Resolve Paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    base_lib_dir = os.path.join(repo_root, TARGET_DIR)
    temp_dir = os.path.join(repo_root, "_temp_deps")

    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)

    # 2. Iterate Versions
    for version in TARGET_VERSIONS:
        # Construct Tag Name
        # Assuming original tag structure "v{version}". Change to "v.{version}" if the upstream repo changed it!
        tag = f"v{version}"
        
        for suffix, local_plat in TARGET_PLATFORMS.items():
            # Construct Asset Name
            # Pattern: openssl-{ver}-{plat}
            asset_name = f"openssl-{version}-{suffix}"
            download_url = f"https://github.com/{REPO_OWNER}/{REPO_NAME}/releases/download/{tag}/{asset_name}"
            
            local_archive = os.path.join(temp_dir, asset_name)
            
            # Download
            if download_file(download_url, local_archive):
                # Target: <repo_root>/lib/openssl/<version>/<platform>/
                final_dest = os.path.join(base_lib_dir, version, local_plat)
                
                # Clean up existing directory if present before fresh extraction
                if os.path.exists(final_dest):
                    shutil.rmtree(final_dest)
                    
                # Extract "as is" directly to destination
                extract_archive(local_archive, final_dest)
                
                # Generate Version Include File for Static Linking
                generate_version_inc(version, final_dest)
                
                log(f"Installed {version} for {local_plat}")
            else:
                log(f"Skipping {version} {local_plat} (Not found or error)")

    # Cleanup
    shutil.rmtree(temp_dir)
    log("Dependency setup complete.")

if __name__ == "__main__":
    main()